/* RetrosynthesisClaw — script.js */

const API_BASE_URL = window.location.origin;
let appConfig = null;
const targetInput = document.getElementById('target');
const topKSelect = document.getElementById('topK');
const debugCheckbox = document.getElementById('debug');
const reasoningToggle = document.getElementById('reasoningToggle');
const submitBtn = document.getElementById('submitBtn');
const loadingDiv = document.getElementById('loading');
const progressPanel = document.getElementById('progressPanel');
const progressBar = document.getElementById('progressBar');
const progressMeta = document.getElementById('progressMeta');
const progressLog = document.getElementById('progressLog');
const errorDiv = document.getElementById('error');
const errorMessage = document.getElementById('errorMessage');
const resultsDiv = document.getElementById('results');
const routesContainer = document.getElementById('routesContainer');
const routeTabs = document.getElementById('routeTabs');
const emptyState = document.getElementById('emptyState');
const ketcherFrame = document.getElementById('ketcherFrame');
const ketcherNotice = document.getElementById('ketcherNotice');
const apiDot = document.getElementById('apiDot');
const apiText = document.getElementById('apiText');
const smilesInput = document.getElementById('smilesInput');
const smilesOutput = document.getElementById('smilesOutput');
const iupacOutput = document.getElementById('iupacOutput');
const formulaOutput = document.getElementById('formulaOutput');
const weightOutput = document.getElementById('weightOutput');
const reasoningPanel = document.getElementById('reasoningPanel');
const reasoningContent = document.getElementById('reasoningContent');
const copyReasoningBtn = document.getElementById('copyReasoningBtn');
const copyBtn = document.getElementById('copyBtn');
const exportBtn = document.getElementById('exportBtn');
const loadSmilesBtn = document.getElementById('loadSmilesBtn');
const copySmilesBtn = document.getElementById('copySmilesBtn');
const exportStructureBtn = document.getElementById('exportStructureBtn');
const sendToRetroBtn = document.getElementById('sendToRetroBtn');
const refreshKetcherBtn = document.getElementById('refreshKetcherBtn');
const syncFromCanvasBtn = document.getElementById('syncFromCanvasBtn');

let currentRoutes = [];
let currentTarget = null;
let currentReasoning = '';
let activeRouteIdx = 0;
let currentPlan = null;

function init() { submitBtn?.addEventListener('click', handleSubmit); copyBtn?.addEventListener('click', copyResults); exportBtn?.addEventListener('click', exportResults); loadSmilesBtn?.addEventListener('click', loadSmiles); copySmilesBtn?.addEventListener('click', () => copyText(smilesOutput?.textContent || '')); exportStructureBtn?.addEventListener('click', exportStructure); sendToRetroBtn?.addEventListener('click', sendStructureToRetro); refreshKetcherBtn?.addEventListener('click', () => ketcherFrame && (ketcherFrame.src = '/standalone/index.html')); syncFromCanvasBtn?.addEventListener('click', syncWorkbench); copyReasoningBtn?.addEventListener('click', () => { copyText(currentReasoning); showToast('推理过程已复制'); }); reasoningToggle?.addEventListener('change', () => { if (reasoningPanel) reasoningPanel.classList.toggle('hidden', !reasoningToggle.checked || !currentReasoning); }); document.addEventListener('click', handleDelegatedClicks); testAPIConnection(); loadAppConfig(); waitForKetcher(); }
async function loadAppConfig() { try { const r = await fetch(`${API_BASE_URL}/config`); if (!r.ok) throw new Error(); appConfig = await r.json(); updateAgentConfigPanels(); } catch (e) { console.warn('loadAppConfig failed', e); } }
async function testAPIConnection() { if (!apiDot || !apiText) return; apiText.textContent = 'Connecting…'; apiDot.className = 'api-dot'; try { const r = await fetch(`${API_BASE_URL}/health`); if (!r.ok) throw new Error(); apiDot.classList.add('connected'); apiText.textContent = 'API Connected'; } catch { apiDot.classList.add('disconnected'); apiText.textContent = 'API Offline'; } }
function waitForKetcher() { const start = Date.now(); const timer = setInterval(() => { if (ketcherFrame?.contentWindow?.ketcher) { clearInterval(timer); showNotice('Ketcher 已就绪，可直接绘制分子结构。'); return; } if (ketcherFrame?.contentWindow?.window?.ketcher) { clearInterval(timer); showNotice('Ketcher 已就绪，可直接绘制分子结构。'); return; } if (Date.now() - start > 8000) { clearInterval(timer); showNotice('未检测到 Ketcher API，请确认 /standalone/index.html 已加载。'); } }, 500); }
function showNotice(msg) { if (!ketcherNotice) return; ketcherNotice.textContent = msg; ketcherNotice.classList.remove('hidden'); }
async function getKetcherInstance() { const k = ketcherFrame?.contentWindow?.ketcher || ketcherFrame?.contentWindow?.window?.ketcher; if (!k) throw new Error('Ketcher 尚未初始化'); return k; }
async function getKetcherSmiles() { const k = await getKetcherInstance(); try { return (await k.getSmiles())?.trim() || ''; } catch (e) { console.warn('Ketcher getSmiles 失败:', e); return ''; } }
async function setKetcherSmiles(smiles) { const k = await getKetcherInstance(); try { await k.setMolecule(smiles); } catch (e) { console.warn('Ketcher setMolecule 失败:', e); } }
async function syncWorkbench() { hideError(); try { const smiles = await getKetcherSmiles(); if (!smiles) return showError('画布为空'); await updateStructureFields(smiles); showToast('结构已同步'); } catch (e) { showError(e.message || '同步失败'); } }
async function loadSmiles() { hideError(); const text = (smilesInput?.value || '').trim(); if (!text) return showError('请输入 SMILES 或名称'); try { const data = await updateStructureFields(text); const canonical = data.canonical_smiles || data.smiles; if (canonical) { try { await setKetcherSmiles(canonical); } catch { } } showToast('结构已加载'); } catch (e) { showError(e.message || '加载失败'); } }
async function updateStructureFields(text) { const r = await fetch(`${API_BASE_URL}/molecule/export`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text }) }); if (!r.ok) throw new Error(`结构导出失败: HTTP ${r.status}`); const data = await r.json(); if (smilesOutput) smilesOutput.textContent = data.canonical_smiles || data.smiles || '—'; if (iupacOutput) iupacOutput.textContent = data.iupac_name || '—'; if (formulaOutput) formulaOutput.textContent = data.molecular_formula || '—'; if (weightOutput) weightOutput.textContent = data.molecular_weight ? Number(data.molecular_weight).toFixed(2) : '—'; if (targetInput) targetInput.value = data.canonical_smiles || data.smiles || text; return data; }
function sendStructureToRetro() { const smiles = smilesOutput?.textContent?.trim(); if (!smiles || smiles === '—') return showError('请先同步结构'); targetInput.value = smiles; showToast('已填入目标分子'); }

async function handleSubmit() { hideError(); const target = (targetInput?.value || '').trim(); if (!target) return showError('请先输入目标分子 SMILES'); const top_k = parseInt(topKSelect?.value || '3', 10); const debug = Boolean(debugCheckbox?.checked); currentRoutes = []; currentTarget = target; activeRouteIdx = 0; currentPlan = null; resetProgress(); showLoading(); showProgress(true); if (emptyState) emptyState.classList.add('hidden'); if (resultsDiv) resultsDiv.classList.add('hidden'); try { await streamRouteProgress({ target, top_k, debug }); } catch (e) { showError(e.message || '合成规划失败'); } finally { hideLoading(); showProgress(false); } }

async function streamRouteProgress({ target, top_k, debug }) { const response = await fetch(`${API_BASE_URL}/route/stream`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ target, top_k, debug }) }); if (!response.ok || !response.body) throw new Error(`HTTP ${response.status}`); const reader = response.body.getReader(); const decoder = new TextDecoder('utf-8'); let buffer = ''; while (true) { const { value, done } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); let idx; while ((idx = buffer.indexOf('\n\n')) >= 0) { const chunk = buffer.slice(0, idx).trim(); buffer = buffer.slice(idx + 2); if (!chunk.startsWith('data: ')) continue; const payload = chunk.slice(6).trim(); if (!payload) continue; try { consumeProgressEvent(JSON.parse(payload)); } catch { } } } }

function consumeProgressEvent(event) { if (!event?.type) return; if (event.type === 'target') { currentTarget = event.target?.canonical_smiles || event.target?.smiles || currentTarget; pushProgress('目标分子已解析'); return; } if (event.type === 'progress') { const ri = Number(event.route_index || 0); const rc = Number(event.route_count || 1); setProgress(rc > 0 ? Math.min((ri - 1) / rc, 1) : 0, event.message || '生成中…'); return; } if (event.type === 'route') { upsertRoute(event.route, event.route_index); const rc = Number(event.route_count || currentRoutes.length || 1); setProgress(rc > 0 ? Math.min(currentRoutes.length / rc, 1) : 1, `已收到 ${currentRoutes.length}/${rc} 条路线`); displayResults({ plan: currentPlan, routes: currentRoutes }); return; } if (event.type === 'execution') { pushProgress(`执行完成: ${event.execution?.status || 'unknown'}`); return; } if (event.type === 'complete') { if (Array.isArray(event.routes)) currentRoutes = event.routes; currentPlan = event.plan || event.synthesis_route || event.retrosynthesis_plan || { routes: currentRoutes }; displayResults(currentPlan); setProgress(1, '路线生成完成'); } }

function upsertRoute(route, routeIndex) { if (!route) return; const id = route.route_id || `route-${routeIndex || currentRoutes.length + 1}`; const normalized = { ...route, route_id: id, _route_index: routeIndex || currentRoutes.length + 1 }; const existing = currentRoutes.findIndex(r => r.route_id === id); if (existing >= 0) currentRoutes[existing] = normalized; else currentRoutes.push(normalized); }

function displayResults(result) { const plan = result?.result || result?.retrosynthesis_plan || result?.synthesis_route || result?.plan || result || {}; const routes = plan?.routes || []; if (!routes.length) { if (emptyState) emptyState.classList.remove('hidden'); return; } currentRoutes = routes; currentPlan = plan; if (emptyState) emptyState.classList.add('hidden'); const firstStep = routes[0]?.steps?.[0]; currentReasoning = safeText(firstStep?.metadata?.reasoning || firstStep?.metadata?.model_response?.reasoning || routes[0]?.metadata?.reasoning || plan?.summary || ''); if (reasoningPanel && reasoningContent) { if (currentReasoning && reasoningToggle?.checked) { reasoningContent.textContent = currentReasoning; reasoningPanel.classList.remove('hidden'); } else { reasoningPanel.classList.add('hidden'); } } buildRouteTabs(routes, plan.selected_route_id || plan.recommended_route_id); renderActiveRoute(plan); renderTargetAnalysis(plan); renderEvaluationSummary(plan); renderPlanSummary(plan); renderExecutionSummary(plan); renderParserPanel(plan); renderEvaluatorPanel(plan); if (resultsDiv) resultsDiv.classList.remove('hidden'); }

function renderTargetAnalysis(plan) { const existing = document.getElementById('targetAnalysisCard'); if (existing) existing.remove(); const panel = document.createElement('div'); panel.id = 'targetAnalysisCard'; panel.className = 'reasoning-card'; const target = plan?.target || plan?.metadata?.target_analysis || {}; const parserMeta = plan?.metadata?.target_parser_metadata || target?.metadata || {}; const risks = Array.isArray(target.risk_flags) ? target.risk_flags : []; const hints = Array.isArray(target.disconnection_hints) ? target.disconnection_hints : []; panel.innerHTML = `<div class="reasoning-header"><span class="reasoning-title">分子解析</span></div><div class="reasoning-body"><div><strong>Input:</strong> ${escapeHtml(target.input_text || currentTarget || '—')}</div><div><strong>SMILES:</strong> <span class="mono">${escapeHtml(target.canonical_smiles || target.smiles || '—')}</span></div><div><strong>Valid:</strong> ${String(target.valid ?? '—')}</div><div><strong>Source Type:</strong> ${escapeHtml(target.source_type || '—')}</div><div><strong>Description:</strong> ${escapeHtml(target.description || '—')}</div><div><strong>Scaffold:</strong> ${escapeHtml(target.scaffold_summary || '—')}</div><div><strong>Functional Groups:</strong> ${escapeHtml((target.functional_groups || []).join(', ') || '—')}</div><div><strong>Ring Systems:</strong> ${escapeHtml((target.ring_systems || []).join(', ') || '—')}</div><div><strong>Fragmentable:</strong> ${String(target.fragmentable ?? '—')}</div><div><strong>Fragment Count:</strong> ${escapeHtml(String(target.fragment_count_estimate ?? target.fragment_count ?? '—'))}</div><div><strong>Confidence:</strong> ${Number(target.fragmentability_confidence ?? target.fragment_confidence ?? 0).toFixed(2)}</div><div><strong>Strategy:</strong> ${escapeHtml(target.recommended_strategy || target.synthetic_complexity || '—')}</div><div><strong>Risks:</strong> ${escapeHtml(risks.join(', ') || '—')}</div><div><strong>Hints:</strong> ${escapeHtml(hints.join(', ') || '—')}</div><div><strong>Parser Notes:</strong> ${escapeHtml(parserMeta.notes || parserMeta.parser || '—')}</div></div>`; resultsDiv?.prepend(panel); }
function renderEvaluationSummary(plan) { const existing = document.getElementById('evaluationSummaryCard'); if (existing) existing.remove(); const panel = document.createElement('div'); panel.id = 'evaluationSummaryCard'; panel.className = 'reasoning-card'; const evalSummary = plan?.metadata?.evaluation_summary || plan?.metadata?.route_comparison?.overall_summary || plan?.summary || '—'; const routeComparison = plan?.metadata?.route_comparison || {}; const criticalAssessments = plan?.metadata?.critical_assessments || []; panel.innerHTML = `<div class="reasoning-header"><span class="reasoning-title">评估结果</span></div><div class="reasoning-body"><div><strong>Summary:</strong> ${escapeHtml(evalSummary)}</div><div><strong>Route Comparison:</strong> ${escapeHtml(routeComparison.overall_summary || '—')}</div><div><strong>Recommended Route:</strong> ${escapeHtml(routeComparison.recommended_route_id || plan?.selected_route_id || '—')}</div><div><strong>Critical Assessments:</strong> ${criticalAssessments.length}</div>${criticalAssessments.length ? criticalAssessments.map((a, idx) => `<div class="fragment-timeline-item ${escapeHtml(a.overall_verdict || 'pending')}"><div class="fragment-timeline-head"><span class="fragment-step-badge">${idx + 1}</span><span class="fragment-state ${escapeHtml(a.overall_verdict || 'pending')}">${escapeHtml(a.overall_verdict || 'pending')}</span><span class="fragment-id">${escapeHtml(a.route_id || 'route')}</span></div><div class="fragment-timeline-body"><div><strong>Feasibility:</strong> ${Number(a.reaction_feasibility || 0).toFixed(2)}</div><div><strong>Plausibility:</strong> ${Number(a.chemical_plausibility || 0).toFixed(2)}</div><div><strong>Substrate:</strong> ${Number(a.substrate_compatibility || 0).toFixed(2)}</div><div><strong>FG Tolerance:</strong> ${Number(a.functional_group_tolerance || 0).toFixed(2)}</div><div><strong>Conditions:</strong> ${Number(a.condition_reasonableness || 0).toFixed(2)}</div><div><strong>Risk:</strong> ${Number(a.side_reaction_risk || 0).toFixed(2)}</div><div><strong>Evidence:</strong> ${Number(a.evidence_strength || 0).toFixed(2)}</div><div><strong>Comments:</strong> ${escapeHtml((a.critical_comments || []).join(' | ') || '—')}</div><div><strong>Failure Modes:</strong> ${escapeHtml((a.failure_modes || []).join(', ') || '—')}</div><div><strong>Improvements:</strong> ${escapeHtml((a.improvement_suggestions || []).join(', ') || '—')}</div></div></div>`).join('') : '—'}</div></div>`; resultsDiv?.prepend(panel); }
function getModelConfigSummary() { const model = appConfig?.api_config || {}; return { provider: appConfig?.model_provider || '—', baseUrl: appConfig?.model_base_url || '—', modelName: appConfig?.model_name || '—', apiPath: appConfig?.model_api_path_template || '—', authScheme: appConfig?.model_auth_scheme || '—', apiKeyHeader: appConfig?.model_api_key_header || '—' }; }
function configSummaryHtml(title, cfg) { return `<div class="config-grid"><div class="config-kv"><span>Provider</span><strong>${escapeHtml(cfg.provider || '—')}</strong></div><div class="config-kv"><span>Model</span><strong>${escapeHtml(cfg.modelName || '—')}</strong></div><div class="config-kv"><span>Base URL</span><strong class="mono">${escapeHtml(cfg.baseUrl || '—')}</strong></div><div class="config-kv"><span>API Path</span><strong class="mono">${escapeHtml(cfg.apiPath || '—')}</strong></div><div class="config-kv"><span>Auth</span><strong>${escapeHtml(cfg.authScheme || '—')}</strong></div><div class="config-kv"><span>Header</span><strong>${escapeHtml(cfg.apiKeyHeader || '—')}</strong></div></div>`; }
function renderParserPanel(plan) { const existing = document.getElementById('parserSummaryCard'); if (existing) existing.remove(); const panel = document.createElement('div'); panel.id = 'parserSummaryCard'; panel.className = 'reasoning-card panel-shell'; const target = plan?.target || plan?.metadata?.target_analysis || {}; const parserMeta = plan?.metadata?.target_parser_metadata || target?.metadata || {}; const cfg = getModelConfigSummary(); panel.innerHTML = `<div class="reasoning-header"><span class="reasoning-title">分子解析面板</span></div><div class="reasoning-body"><div class="panel-section-title">Agent 配置</div><div id="parserConfigSummary">${configSummaryHtml('Parser', cfg)}</div><div class="panel-section-title">解析结果</div><div><strong>Parser:</strong> ${escapeHtml(parserMeta.parser || 'llm')}</div><div><strong>Valid:</strong> ${String(target.valid ?? '—')}</div><div><strong>Fragmentable:</strong> ${String(target.fragmentable ?? '—')}</div><div><strong>Fragment Count:</strong> ${escapeHtml(String(target.fragment_count_estimate ?? target.fragment_count ?? '—'))}</div><div><strong>Fragment Confidence:</strong> ${Number(target.fragmentability_confidence ?? target.fragment_confidence ?? 0).toFixed(2)}</div><div><strong>Risks:</strong> ${escapeHtml((target.risk_flags || []).join(', ') || '—')}</div><div><strong>Hints:</strong> ${escapeHtml((target.disconnection_hints || []).join(', ') || '—')}</div><div><strong>Notes:</strong> ${escapeHtml(parserMeta.notes || target.fragment_rationale || '—')}</div></div>`; resultsDiv?.prepend(panel); }
function renderEvaluatorPanel(plan) { const existing = document.getElementById('evaluatorSummaryCard'); if (existing) existing.remove(); const panel = document.createElement('div'); panel.id = 'evaluatorSummaryCard'; panel.className = 'reasoning-card panel-shell'; const bundle = plan?.metadata?.evaluation_bundle || {}; const comparison = plan?.metadata?.route_comparison || bundle?.route_comparison || {}; const criticalAssessments = plan?.metadata?.critical_assessments || bundle?.critical_assessments || []; const cfg = getModelConfigSummary(); panel.innerHTML = `<div class="reasoning-header"><span class="reasoning-title">评估面板</span></div><div class="reasoning-body"><div class="panel-section-title">Agent 配置</div><div id="evaluatorConfigSummary">${configSummaryHtml('Evaluator', cfg)}</div><div class="panel-section-title">评估结果</div><div><strong>Bundle Summary:</strong> ${escapeHtml(plan?.metadata?.evaluation_summary || bundle?.summary || '—')}</div><div><strong>Comparison:</strong> ${escapeHtml(comparison.overall_summary || '—')}</div><div><strong>Recommended Route:</strong> ${escapeHtml(comparison.recommended_route_id || plan?.selected_route_id || '—')}</div><div><strong>Critical Count:</strong> ${criticalAssessments.length}</div>${criticalAssessments.length ? criticalAssessments.map((a, idx) => `<div class="fragment-timeline-item ${escapeHtml(a.overall_verdict || 'pending')}"><div class="fragment-timeline-head"><span class="fragment-step-badge">${idx + 1}</span><span class="fragment-state ${escapeHtml(a.overall_verdict || 'pending')}">${escapeHtml(a.overall_verdict || 'pending')}</span><span class="fragment-id">${escapeHtml(a.route_id || 'route')}</span></div><div class="fragment-timeline-body"><div><strong>Feasibility:</strong> ${Number(a.reaction_feasibility || 0).toFixed(2)}</div><div><strong>Plausibility:</strong> ${Number(a.chemical_plausibility || 0).toFixed(2)}</div><div><strong>Substrate:</strong> ${Number(a.substrate_compatibility || 0).toFixed(2)}</div><div><strong>FG Tolerance:</strong> ${Number(a.functional_group_tolerance || 0).toFixed(2)}</div><div><strong>Conditions:</strong> ${Number(a.condition_reasonableness || 0).toFixed(2)}</div><div><strong>Risk:</strong> ${Number(a.side_reaction_risk || 0).toFixed(2)}</div><div><strong>Evidence:</strong> ${Number(a.evidence_strength || 0).toFixed(2)}</div></div></div>`).join('') : '—'}</div></div>`; resultsDiv?.prepend(panel); }
function renderPlanSummary(plan) { const existing = document.getElementById('planSummaryCard'); if (existing) existing.remove(); const panel = document.createElement('div'); panel.id = 'planSummaryCard'; panel.className = 'reasoning-card'; const target = plan?.target || {}; panel.innerHTML = `<div class="reasoning-header"><span class="reasoning-title">路线生成面板</span></div><div class="reasoning-body"><div class="panel-section-title">路线概览</div><div><strong>Summary:</strong> ${escapeHtml(plan?.summary || '—')}</div><div><strong>Selected Route:</strong> ${escapeHtml(plan?.selected_route_id || plan?.recommended_route_id || '—')}</div><div><strong>Execution Status:</strong> ${escapeHtml(plan?.execution_status || 'pending')}</div><div><strong>Route Count:</strong> ${escapeHtml(String(plan?.routes?.length || currentRoutes.length || '—'))}</div><div class="panel-section-title">目标信息</div><div><strong>Target Complexity:</strong> ${escapeHtml(target.synthetic_complexity || target.metadata?.synthetic_complexity || '—')}</div><div><strong>Fragmentable:</strong> ${String(target.fragmentable ?? '—')}</div></div>`; resultsDiv?.prepend(panel); }
function renderExecutionSummary(plan) { const existing = document.getElementById('executionSummaryCard'); if (existing) existing.remove(); const panel = document.createElement('div'); panel.id = 'executionSummaryCard'; panel.className = 'reasoning-card'; const fragments = plan?.execution_fragments || []; panel.innerHTML = `<div class="reasoning-header"><span class="reasoning-title">执行结果面板</span></div><div class="reasoning-body"><div class="panel-section-title">执行状态</div><div><strong>Count:</strong> ${fragments.length}</div><div><strong>Status:</strong> ${escapeHtml(plan?.execution_status || 'pending')}</div><div class="panel-section-title">Fragments</div><div style="margin-top:8px">${fragments.length ? fragments.map((f, idx) => `<div class="fragment-timeline-item ${escapeHtml(f.status || 'pending')}"><div class="fragment-timeline-head"><span class="fragment-step-badge">${idx + 1}</span><span class="fragment-state ${escapeHtml(f.status || 'pending')}">${escapeHtml(f.status || 'pending')}</span><span class="fragment-id">${escapeHtml(f.fragment_id)}</span></div><div class="fragment-timeline-body"><div><strong>Strategy:</strong> ${escapeHtml(f.strategy || '—')}</div><div><strong>SMILES:</strong> <span class="mono">${escapeHtml(f.fragment_smiles || '—')}</span></div><div><strong>Instructions:</strong> ${escapeHtml(f.instructions || '—')}</div><div><strong>Confidence:</strong> ${Number(f.confidence || 0).toFixed(2)}</div>${f.result ? `<pre class="fragment-result-json">${escapeHtml(JSON.stringify(f.result, null, 2))}</pre>` : ''}</div></div>`).join('') : '—'}</div></div>`; resultsDiv?.prepend(panel); }
function buildRouteTabs(routes, selectedId) { if (!routeTabs) return; routeTabs.innerHTML = ''; routes.forEach((route, i) => { const score = Number(route.total_score || route.score || 0).toFixed(0); const tab = document.createElement('button'); tab.className = 'route-tab' + (route.route_id === selectedId || i === activeRouteIdx ? ' active' : ''); tab.innerHTML = `路线 ${i + 1} <span class="tab-score">${score}</span>`; tab.addEventListener('click', () => { activeRouteIdx = i; routeTabs.querySelectorAll('.route-tab').forEach((t, j) => t.classList.toggle('active', j === i)); renderActiveRoute(currentPlan || { routes }); }); routeTabs.appendChild(tab); }); }
function renderActiveRoute(plan) { if (!routesContainer || !currentRoutes.length) return; const route = currentRoutes[activeRouteIdx] || currentRoutes[0]; routesContainer.innerHTML = ''; routesContainer.appendChild(createPathwayView(route, activeRouteIdx + 1, plan)); }
function createPathwayView(route, _routeNumber, plan) { const steps = route.steps || []; const score = Number(route.total_score || route.score || 0).toFixed(1); const feasib = Number(route.feasibility_score || 0); const wrap = document.createElement('div'); const synthesisStrategy = route.metadata?.synthesis_strategy || ''; const targetAnalysis = plan?.target || route.metadata?.target_analysis || {}; wrap.innerHTML = `<div class="route-header-bar"><div class="route-header-left"><span class="score-pill"><svg viewBox="0 0 16 16" fill="currentColor"><path d="M8 1l1.9 3.9 4.3.6-3.1 3 .7 4.3L8 10.8l-3.8 2 .7-4.3-3.1-3 4.3-.6z"/></svg>${score}</span><span class="route-feasibility">可行性 ${(feasib * 100).toFixed(0)}% · ${steps.length} 步</span></div></div>${synthesisStrategy ? `<div class="synthesis-strategy"><h4>Synthesis Strategy</h4><p>${escapeHtml(synthesisStrategy)}</p></div>` : ''}${targetAnalysis?.description ? `<div class="synthesis-strategy"><h4>Target Analysis</h4><p>${escapeHtml(targetAnalysis.description)}</p></div>` : ''}`; const pathway = document.createElement('div'); pathway.className = 'pathway'; steps.forEach((step, i) => { pathway.appendChild(createPathwayStep(step, i, steps.length)); if (i < steps.length - 1) { const conn = document.createElement('div'); conn.className = 'step-connector'; pathway.appendChild(conn); } }); if (route.target_smiles) { const targetRow = document.createElement('div'); targetRow.className = 'target-mol-row'; targetRow.innerHTML = `<div class="step-connector"></div><div class="target-label-row"><span class="target-badge">目标产物</span></div><div class="product-row">${makeMolCard(route.target_smiles, '目标分子', true)}</div>`; pathway.appendChild(targetRow); } wrap.appendChild(pathway); requestAnimationFrame(() => loadAllMolImages(wrap)); steps.forEach(step => schedulePredictYield(wrap, step)); return wrap; }
function createPathwayStep(step, stepIdx) { const inputSmiles = cleanInputSmiles(step.input_smiles); const conditions = safeText(step.conditions); const rxnType = safeText(step.reaction_type) || '反应'; const node = document.createElement('div'); node.className = 'pathway-step'; node.dataset.stepIndex = String(step.step_index || stepIdx + 1); const reactantsHtml = inputSmiles.length ? inputSmiles.map((smi, i) => (i > 0 ? '<div class="reactant-plus">+</div>' : '') + makeMolCard(smi, `反应物 ${i + 1}`, false)).join('') : makeMolCard('', '反应物', false); node.innerHTML = `<div class="reactants-row">${reactantsHtml}</div><div class="reaction-arrow-block"><div class="arrow-top-row"><span class="arrow-step-badge">Step ${step.step_index || stepIdx + 1}</span><span class="arrow-reaction-type">${escapeHtml(rxnType)}</span></div><div class="arrow-shaft-wrap"><div class="arrow-line"></div><div class="arrow-head"></div></div><div class="arrow-bottom-row">${conditions ? `<span class="cond-badge">${escapeHtml(conditions)}</span>` : ''}<span class="yield-badge" data-yield-container data-step-index="${step.step_index || stepIdx + 1}"><span class="yield-loading"><span class="yield-spinner"></span>预测产率…</span></span></div></div>`; return node; }
function makeMolCard(smiles, label, isProduct) { const cls = isProduct ? 'mol-card product-card' : 'mol-card'; const safe = escapeHtml(smiles || ''); const size = isProduct ? 200 : 160; return `<div class="${cls}"><div class="mol-card-img" data-smiles="${safe}" data-size="${size}"><div class="img-placeholder"><span>加载中</span></div></div><div class="mol-card-footer"><div class="mol-card-label">${escapeHtml(label)}</div>${smiles ? `<div class="mol-card-smiles" title="${safe}" onclick="copyText('${safe}')">${safe.length > 40 ? safe.slice(0, 38) + '…' : safe}</div>` : ''}</div></div>`; }
function loadAllMolImages(container) { container.querySelectorAll('.mol-card-img[data-smiles]').forEach(cell => { const smiles = cell.dataset.smiles; const size = cell.dataset.size || '160'; if (!smiles) return; const img = document.createElement('img'); img.src = `${API_BASE_URL}/molecule/image?smiles=${encodeURIComponent(smiles)}&width=${size}&height=${size}&t=${Date.now()}`; img.alt = smiles; img.style.cssText = 'max-width:100%;max-height:100%;object-fit:contain;padding:8px;'; img.onerror = () => { cell.innerHTML = `<div class="img-placeholder"><span>无图像</span></div>`; }; cell.innerHTML = ''; cell.appendChild(img); }); }
function schedulePredictYield(container, step) { const productSmiles = step.product_smiles || ''; const inputSmiles = cleanInputSmiles(step.input_smiles); if (!productSmiles || !inputSmiles.length) return; if (!isValidSmiles(productSmiles) || !isValidSmiles(inputSmiles.join('.'))) return; const known = step.predicted_yield ?? step.yield_prediction ?? step.yield ?? null; if (known !== null && known !== undefined && known !== '') { updateYieldBadge(container, step.step_index, Number(known)); return; } fetch(`${API_BASE_URL}/yield/predict`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ reactant_smiles: inputSmiles.join('.'), product_smiles: productSmiles }) }).then(r => r.ok ? r.json() : null).then(data => { if (data?.predicted_yield !== undefined) updateYieldBadge(container, step.step_index, Number(data.predicted_yield)); else hideYieldBadge(container, step.step_index); }).catch(() => hideYieldBadge(container, step.step_index)); }
function updateYieldBadge(container, stepIndex, yieldVal) { const badge = container.querySelector(`[data-yield-container][data-step-index="${stepIndex}"]`); if (!badge) return; if (Number.isNaN(yieldVal)) { hideYieldBadge(container, stepIndex); return; } badge.innerHTML = `${yieldVal.toFixed(1)}%`; }
function hideYieldBadge(container, stepIndex) { const badge = container.querySelector(`[data-yield-container][data-step-index="${stepIndex}"]`); if (badge) badge.style.display = 'none'; }
function safeText(text) { if (!text || typeof text !== 'string') return ''; const t = text.trim(); if (t.startsWith('{') || t.startsWith('[')) return ''; return t; }
function isValidSmiles(text) { if (!text || typeof text !== 'string') return false; const t = text.trim(); if (!t) return false; if (['_precursor', '_product', '_target', ' ', '\n', '\t', '_'].some(p => t.includes(p))) return false; return /^[A-Za-z0-9+\-\[\]\(\)\=#@\/\.\:\\%$!&*;',~`|<>{}]+$/.test(t); }
function cleanInputSmiles(inputSmiles) { if (!inputSmiles) return []; const arr = Array.isArray(inputSmiles) ? inputSmiles : [String(inputSmiles)]; return arr.map(p => (typeof p === 'string' ? p.trim() : '')).filter(p => p.length > 0 && isValidSmiles(p)); }
function escapeHtml(text) { if (!text) return ''; const d = document.createElement('div'); d.textContent = text; return d.innerHTML; }
function copyText(text) { navigator.clipboard.writeText(text).then(() => showToast('已复制到剪贴板')).catch(() => showError('复制失败')); }
function updateAgentConfigPanels() { const parserCfg = document.getElementById('parserConfigSummary'); const evaluatorCfg = document.getElementById('evaluatorConfigSummary'); const cfg = getModelConfigSummary(); const html = configSummaryHtml('Agent', cfg); if (parserCfg) parserCfg.innerHTML = html; if (evaluatorCfg) evaluatorCfg.innerHTML = html; }
function handleDelegatedClicks(event) { const target = event.target?.closest?.('[data-copy-smiles]'); if (!target) return; const value = target.getAttribute('data-copy-smiles') || ''; if (value) copyText(value); }
function showToast(message, type = 'success') { const container = document.getElementById('toastContainer'); if (!container) return; const toast = document.createElement('div'); toast.className = 'toast'; toast.innerHTML = `<div class="toast-dot ${type === 'error' ? 'error' : ''}"></div><span>${escapeHtml(message)}</span>`; container.appendChild(toast); setTimeout(() => { toast.classList.add('removing'); setTimeout(() => toast.remove(), 250); }, 3000); }
function showError(message) { if (!errorDiv || !errorMessage) return; errorMessage.textContent = message; errorDiv.classList.remove('hidden'); }
function hideError() { errorDiv?.classList.add('hidden'); }
function showLoading() { loadingDiv?.classList.remove('hidden'); }
function hideLoading() { loadingDiv?.classList.add('hidden'); }
function showProgress(show) { progressPanel?.classList.toggle('hidden', !show); }
function resetProgress() { if (progressLog) progressLog.innerHTML = ''; setProgress(0, '等待模型输出…'); }
function setProgress(ratio, message) { if (progressBar) progressBar.style.width = `${Math.max(0, Math.min(1, ratio)) * 100}%`; if (progressMeta) progressMeta.textContent = message; pushProgress(message); }
function pushProgress(message) { if (!progressLog) return; const row = document.createElement('div'); row.className = 'progress-item'; row.textContent = message; progressLog.appendChild(row); progressLog.scrollTop = progressLog.scrollHeight; }
function exportResults() { const data = JSON.stringify({ target: currentTarget, plan: currentPlan, routes: currentRoutes }, null, 2); const blob = new Blob([data], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = Object.assign(document.createElement('a'), { href: url, download: `retrosynthesis_plan_${Date.now()}.json` }); a.click(); URL.revokeObjectURL(url); showToast('已导出 JSON'); }
function exportStructure() { const smiles = smilesOutput?.textContent?.trim(); if (!smiles || smiles === '—') return showError('请先加载结构'); const blob = new Blob([smiles], { type: 'text/plain' }); const url = URL.createObjectURL(blob); const a = Object.assign(document.createElement('a'), { href: url, download: `molecule_${Date.now()}.smiles` }); a.click(); URL.revokeObjectURL(url); showToast('已导出 SMILES'); }
function copyResults() { copyText(JSON.stringify({ target: currentTarget, plan: currentPlan, routes: currentRoutes }, null, 2)); }
document.addEventListener('DOMContentLoaded', init);
